# iPool Pilot BSP layer (custom RK3568 "SZ3568" board)
# SPDX-License-Identifier: MIT

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ipool"
BBFILE_PATTERN_ipool = "^${LAYERDIR}/"
# Higher than meta-rockchip (1) so our bbappends/machine win.
BBFILE_PRIORITY_ipool = "10"

LAYERVERSION_ipool = "1"
LAYERSERIES_COMPAT_ipool = "whinlatter"

# We build on top of the community Rockchip BSP layer.
LAYERDEPENDS_ipool = "core rockchip"
